### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SirLeezus** [MinecraftLibraries/NPCLib#122]
So it works perfect, I just had a few questions.

1. How would I go about making NPC look at the player at all times?
2. When a player joins and the NPC is created the NPC name is shown in tablist for about 3-5secs, how would I go about never allowing the NPC name to be shown in the tablist?

Thank you for the API, it's been helping me a ton with learning NPCs.

**Comment by Chibilena** [comment]
Yes, I would also like to know whether it is possible, there is no such thing in the tablist position.

Just as if it is possible that the NPC looks at a player with his head as soon as he is nearby.

**Comment by JitseB** [comment]
It is added to the lab list for a brief moment. This has to happen because it's a fake player joining the server (using packets, so not really). That's why the name is in gray ;)

You can use the look at method which is added in the latest release (2.11) to look at a location, using some basic math you can make it look at a player.
