### ISSUE TITLE
Unexpected Packet Problem After Implementing NPCLib.

### ISSUE THREAD

**Issue by TheJavaHacker** [MinecraftLibraries/NPCLib#147]
**Describe the bug**

Players are unable to connect to the Spigot-Side server after implementing NPCLib in my Survival Core.

**NPCLib usage option**
NPCLib can be used in multiple ways, please provide [the number](https://github.com/JitseB/NPCLib#usage) corresponding to your usage option.

Didn't follow any of the examples.

**NPCLib JAR name**
npclib-plugin-2.12-SNAPSHOT.jar

**Server version**
E.g. CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (use command `/version`)

CraftBukkit version git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**To Reproduce**
Snippet of the code: https://paste.md-5.net/abizufanoy.cs
Error on BungeeCord side: 
```
[TheJavaHacker] <-> ServerConnector [Survival] has connected
02:05:49 [SEVERE] [TheJavaHacker] <-> ServerConnector [Survival] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
19667b227472616e736c617465223a22
02:05:49 [INFO] [TheJavaHacker] <-> ServerConnector [Survival] has disconnected
```

No known error on Spigot console.

**Expected behavior**

NPCs should be created in their dedicated location & should be shown to players upon joining the server.

**Screenshots**
Unable to provide. Didn't get very far.

**Additional context**

**Comment by JasperJH** [comment]
I ran into the same issue last night and after playing around with the library a bit and putting the server into debug mode, I noticed that there is a NPE on [this](https://github.com/MinecraftLibraries/NPCLib/blob/3e08630cb228e759c2f13078f2c6710ddbd7a7dc/api/src/main/java/com/comphenix/tinyprotocol/TinyProtocol.java#L350 ) line. 

This happens because the GameProfile that is present in the PacketLoginInStart does not actually contain an id and merely contains the name of the player that is trying to join ([source](https://wiki.vg/Protocol#Login_Start)). This was a recent change which was made with [this](https://github.com/MinecraftLibraries/NPCLib/commit/3e08630cb228e759c2f13078f2c6710ddbd7a7dc#diff-4d807c598a0b00580aedbda31e5e5dc04c2951c1fff0286c694c507184ce6e18) commit. Using the latest release, which does not contain that commit, or changing the UUIDs to names again in the TinyProtocol class will fix your issue.

If I have the time I will create a PR to undo that change.

**Comment by JitseB** [comment]
So, the user joins and there is a name but no UUID. After all this time, they still managed to do that.

Ugh...

I will make sure to put the TinyProtocol on the right event, because I'm not planning on changing it back to names.

**Comment by JitseB** [comment]
I don't see why Minecraft made it that the username is the first info they send to the server. I will change it to where it uses the username for initial channel handling and then change it to the UUID when the user is 'fully' joined.

**Comment by JitseB** [comment]
Actually, I will keep it the way it was (with the names), it's only for when the player is online and not for permanent storage. Assuming there won't be developers changing the GameProfiles to have similar names, I don't expend any problems.

I'll be posting an update shortly. Closing issue.

**Comment by JitseB** [comment]
You may download the new pre-release here: https://github.com/MinecraftLibraries/NPCLib/releases/tag/2.12.1-SNAPSHOT
I am currently deploying it to the Maven repo. Good day!
