### ISSUE TITLE
NPC hide from tablist time

### ISSUE THREAD

**Issue by divad-d** [MinecraftLibraries/NPCLib#148]
I wanted to ask if there is a possibility to define/reduce the ticks of removing the npc from the tablist.
Version: Paperspigot 1.8.8

**Comment by JitseB** [comment]
In my experience is reducing the amount of ticks before sending the player hide info packet (so that their name is no longer visible in the tab list) is not beneficial as it potentially leads to hidden NPCs. This is because the player who the packets are sent to has not fully been loaded in to the world yet. This is especially an issue for high-latency players.

However, I would like to invite you to fork the project (and potentially make a pull request) to see where you can take this limit in regards of reducing the amount of ticks before sending this packet.

Closing issue for now.
