### ISSUE TITLE
Can't see NPC since latest version with iDisguise

### ISSUE THREAD

**Issue by thisisfel1x** [MinecraftLibraries/NPCLib#81]
Hey,
I found a bug with another plugin called 'iDisguise'.
Since the latest Version 2.6, the NPC gets invisible, but you can see the Text. If the iDisguise plugin is disabled, it works fine. I implemented both plugins in my minigame.
I don't know if its possible to fix, but it works fine with an older version of NPCLib.

Screenshot: [Screen](https://imgur.com/a/F1Hz9f2)
iDisguise on GitHub: [GitHub](https://github.com/robingrether/iDisguise)

Versions used: NPCLib 2.6, PaperSpigot 1.8.8 (also buggy on Spigot 1.8.8)

EDIT: Links now work.

**Comment by JitseB** [comment]
Hi, thanks for opening this issue ticket!

Good that you found the root cause of the issue you were troubling with a while back! Now we can start solving it.

When does the NPC get invisible? Is it always invisible? Or is it when you disguise? This might have to do with the UUID of the NPC which's been changed after 2.6 for LabyMod.

**Comment by thisisfel1x** [comment]
iDisguise loaded:
I join and the NPC is invisible. Permanently. I'm not disguise or anything.

iDisguise not loaded:
All works fine, I can see my NPC after joining. 

I'm a bit confused that all worked fine to 2.4.2. Then I updated to 2.6. I'm not sure if this bug happens on e.g. version 2.5.

**Comment by JitseB** [comment]
Well it would make sense. Let me see if I can find UUID tracking in iDisguise.

**Comment by JitseB** [comment]
Okay, iDisguise is a bit of a mess. Would you mind trying NPCLib version 2.5-SNAPSHOT to see if it does occur on this version as well? If so, I'll add a method to enable LabyMod and it'll clear this issue.

**Comment by thisisfel1x** [comment]
I tested the version 2.5.2. It works absolutely fine.
I think the root of the problem is the tablist update. Maybe iDisguise can't get along with the prefixes. 
I try to configure the config file and see if it works if I change something

**Comment by JitseB** [comment]
Were you able to find something helpful while changing the config file?

**Comment by thisisfel1x** [comment]
Sadly, nothing changed. Still not able to see the NPC while having iDisguise activated.

**Comment by JitseB** [comment]
Any updates on this issue? I've been busy for some time.

I don't think iDisguise would hide the NPCs because of the prefixes, that seems illogical.

Oh. What might be possible though, is that iDisguise is sending the NPC some kind of packet, updating the state of the entity. Resulting in a hidden NPC. But that seems quite far-fetched.

**Comment by thisisfel1x** [comment]
Okay, I switched to LibsDisguise.
I don't know the exact reason of the issue, but I suppose it's related with the scoreboard/tab prefix.

Thanks for your support!
